### ISSUE TITLE
Memory usage high, and memory not being released soon enough

### ISSUE THREAD

**Issue by MrBlueHere** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#30]
Hi,

My problem is that, when doing scan operation, memory usage climbs a lot. Memory does get released eventually, but it takes a lot of time and it causes problems when scanning with high dpi and feeder. What happens is that with every new page scanner, memory climbs higher and higher. Eventually, there is not enough continuous memory to process the image, and it fails with:

Saraff.Twain.TwainException: Exception of type 'System.OutOfMemoryException' was thrown. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BinaryWriter.Write(Byte[] buffer, Int32 index, Int32 count)
   at Saraff.Twain._ImageHandler.PtrToStreamCore(IntPtr ptr, Stream stream)
   at Saraff.Twain.DibToImage.PtrToStreamCore(IntPtr ptr, Stream stream)
   at Saraff.Twain._ImageHandler.PtrToStream(IntPtr ptr, IStreamProvider provider)
   at Saraff.Twain.Twain32._NativeTransferPictures()
   at Saraff.Twain.Twain32._TwCallbackProcCore(TwMSG msg, Action`1 endAction)
   at Saraff.Twain.Twain32._MessageFilter.PreFilterMessage(Message& m)
   --- End of inner exception stack trace ---
   at ScanApp.TWAIN.TwainScannerDevice.ScanPageTWAIN(Single dpi, String pixelType, String source, String payload, Scanner scanner)
   at ScanApp.Models.ScanOperation.GetPages(String id, Int32 dpi, String pixelType, String source, String payload)

Sample of my code:

```
using (Twain32 _twain32 = new Twain32())
            {
                _twain32.IsTwain2Enable = false;
                _twain32.ShowUI = false;
                _twain32.OpenDSM();

                try
                {
                    _twain32.SourceIndex = scanner.TwainIndex;
                    _twain32.OpenDataSource();
                }
               catch (TwainException ex)
                {
                     // ...
                }
                _twain32.AcquireError += (sender, e) =>
                {
                    if (e.Exception.Data.Contains("FriendlyErrorMessage"))
                    {
                        TwainAcquireError = e.Exception;
                    }
                    else
                    {
                        string friendlyMessage = TwainExceptionTranslator.GetMessageFromException(e.Exception);
                        e.Exception.Data.Add("FriendlyErrorMessage", friendlyMessage);
                        TwainAcquireError = e.Exception;
                    }
                };

                _twain32.EndXfer += (sender, e) =>
                {
                    TimeSpan timeTaken = DateTime.Now - startTime;

                    string scanName = PageFileNameGenerator.CreateNewPageFileName(scanningcDir);

                    using (Image img = e.Image)
                    {
                        img.Save(scanName, ImageFormat.Jpeg);
                    }

                    // Notify about new page
                    string pageId = Path.GetFileNameWithoutExtension(scanName);
                    Events.OnPageEvent(new Events.PageInfo
                    {
                        PageId = pageId,
                        Dpi = (int)dpi,
                        PixelType = pixelType,
                        Source = source,
                        Payload = payload,
                        Scanner = scanner,
                        TimeTaken = timeTaken.ToString()
                    });

                    startTime = DateTime.Now;               // Adjust starting time for next page
                };

                this.SetDeviceSource(_twain32, source, scanner, payload);

                this.SetDeviceProperties(_twain32, dpi, pixelType, scanner, payload);
                
                _twain32.Capabilities.Indicators.Set(false);

                // Scanning starts here
                try
                {
                    startTime = DateTime.Now;
                    _twain32.Acquire();
                }
                finally
                {
                    _twain32.CloseDataSource();

                    if (TwainAcquireError != null)
                    {
                        throw TwainAcquireError;
                    }
                }
            }
        }
```
Is it enough, if I'm just doing 
```
using (Image img = e.Image)
    {
         img.Save(scanName, ImageFormat.Jpeg);
    }
```
to release the memory, or am I missing something?

Thank you and have a nice day

**Comment by MrBlueHere** [comment]
Sorry, I though the first issue wasn't created.
